import sys
import os

Import("environment")

# Use this to try and force the use of Cocoa/GNUStep.
use_cocoa = False

# Use this to force pthreads on Posix platforms, even if they 
# have a different native interface, such as Darwin/OS X
prefer_pthreads = False

if (sys.platform == "darwin" or use_cocoa) and not prefer_pthreads:
    libathena_thread = environment.SharedLibrary("athena_thread", ["thread_cocoa.m"], FRAMEWORKS = ["Foundation"])
elif sys.platform.startswith("haiku") and not prefer_pthreads:
	libathena_thread = environment.SharedLibrary("athena_thread", ["thread_haiku.cpp"], LIBS = ["be"])
elif os.name == "posix" or prefer_pthreads:
    libathena_thread = environment.SharedLibrary("athena_thread", ["thread_pthreads.c"], LIBS = ["pthread"])
elif sys.platform.startswith("win"):
    libathena_thread = environment.Library("athena_thread", ["thread_win32.c"])    
    
Return("libathena_thread")
