import sys

Import("environment")

has_sndio = False

# Set this to True to ignore the existence of sndio headers.
no_sndio = True

l_env = environment.Clone()

configure = Configure(l_env)

if not no_sndio and configure.CheckCHeader("sndio.h"):
    athena_audio = environment.SharedLibrary("athena_audio", ["audio_sndio.c"], LIBS = ["sndio"])
elif sys.platform.startswith("haiku"):
    athena_audio = environment.SharedLibrary("athena_audio", ["audio_haiku.cpp"], LIBS = ["be", "game"])
elif sys.platform == 'darwin':
    athena_audio = environment.SharedLibrary("athena_audio", ["audio_openal.c"], FRAMEWORKS = ["OpenAL"])
else:
    if sys.platform.startswith("win") or sys.platform.startswith("cyg"):
        al_lib = "openal32"
    else:
        al_lib = "openal"
    athena_audio = environment.SharedLibrary("athena_audio", ["audio_openal.c"], LIBS = [al_lib])

l_env = configure.Finish()

Return("athena_audio")
