Import("environment turbojson")

platform = SConscript(dirs = ["platform"], exports = ["environment"])

libathena = environment.StaticLibrary("athena", 
    [
        "game.c", "ai.c", "unit.c", "tile.c", "tileset.c", "spriteset.c", "field.c", "collision.c", 
        "animation.c", "image.c", "load_png.c", "load_tga.c", "container.c", "turbo_json_helpers.c"
    ], 
    LIBS = [platform, "png", turbojson])

athena = environment.Program("athena", ["athena.c"], LIBS = [platform, "png", libathena, turbojson])
athena_test = environment.Program("athena_test", ["athena_test.c"], LIBS = [platform, "png", libathena, turbojson])
athena_image_test = environment.Program("athena_image_test", ["athena_image_test.c"], LIBS = [platform, "png", libathena, turbojson])

Return("athena")
