Import("environment turbojson")

platform = SConscript(dirs = ["platform"], exports = ["environment"])

libathena = environment.StaticLibrary("athena", 
    [
        "game.c", "ai.c", "unit.c", "tile.c", "tileset.c", "spriteset.c", "field.c", "collision.c", "player.c",
        "animation.c", "image.c", "load_png.c", "load_tga.c", "window_style.c", "container.c", "font.c",
        "turbo_json_helpers.c",
        "server_thread.c", "ui_thread.c"
    ],
    LIBS = [platform, "png", turbojson], CPPDEFINES = ["EMBED_CYNICAL"])

athena_libs = [platform, "png", libathena, turbojson]

athena = environment.Program("athena", ["athena.c"], LIBS = athena_libs)
athena_test = environment.Program("athena_test", ["athena_test.c"], LIBS = athena_libs)
athena_image_test = environment.Program("athena_image_test", ["athena_image_test.c"], LIBS = athena_libs)
athena_camera_test = environment.Program("athena_camera_test", ["athena_camera_test.c"], LIBS = athena_libs)

Return("athena")
