import os
import sys

Import("environment turbojson")

s_env = environment.Clone()

platform = SConscript(dirs = ["platform"], exports = ["environment"])

athena_libs = [platform, "png", "z", turbojson, "opus", "ogg"]

if sys.platform.startswith("linux"):
    athena_libs = athena_libs + ["m"]    

libathena = environment.StaticLibrary("athena", 
    [
        "game.c", "ai.c", "unit.c", "tile.c", "tileset.c", "spriteset.c", "field.c", "collision.c", "player.c",
        "animation.c", "image.c", "load_png.c", "load_tga.c", "window_style.c", "container.c", "font.c", "viewport.c",
        "turbo_json_helpers.c", "button.c", "menu.c", "load_opus.c", "audio_ctl.c", "unit_classes.c", "pathfind.c",
        "server_thread.c", "ui_thread.c",
	"options.c", "titlescreen.c",
        "sgi_screen.c", "cynical.c"
    ],
    LIBS = athena_libs)

athena_libs = [libathena] + athena_libs

def AthenaProgram(Name):
    return environment.Program(Name, [Name + ".c"], LIBS = athena_libs)

AthenaProgram("athena")
AthenaProgram("athena_test")
AthenaProgram("athena_camera_test")
AthenaProgram("athena_unit_test")
AthenaProgram("athena_titlescreen_test")

environment = s_env.Clone()

Return("libathena")
